export const ACTION_FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const ACTION_POST_NEW_MESSAGE = "POST_NEW_MESSAGE";
export const ACTION_SHOW_USERNAME_MODAL = "SHOW_USERNAME_MODAL";
export const ACTION_SET_USERNAME = "SET_USERNAME";
