export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const POST_NEW_MESSAGE = "POST_NEW_MESSAGE";
export const SHOW_USERNAME_MODAL = "SHOW_USERNAME_MODAL";
export const SET_USERNAME = "SET_USERNAME";
